{{- if not .Values.keycloak.credentials.existingSecret }}

{{- $secretName := include "keycloak.adminSecretName" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}

{{- $username := .Values.keycloak.credentials.username | default "admin" }}
{{- $password := "" }}

{{- if .Values.keycloak.credentials.password }}
  {{- $password = .Values.keycloak.credentials.password }}
{{- else if and $existingSecret (hasKey $existingSecret.data "password") }}
  {{- $password = index $existingSecret.data "password" | b64dec }}
{{- else }}
  {{- $password = randAlphaNum 32 }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
  username: {{ $username | b64enc | quote }}
  password: {{ $password | b64enc | quote }}

{{- end }}

