apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  {{- if not .Values.keycloak.autoscaling.enabled }}
  replicas: {{ .Values.keycloak.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if and .Values.keycloak.tls.enabled (not .Values.keycloak.tls.existingSecret) }}
      annotations:
        checksum/keycloak-cert: {{ include (print $.Template.BasePath "/keycloak/cert-secret.yaml") . | sha256sum }}
      {{- end }}
      labels:
        {{- include "keycloak.labels" . | nindent 8 }}
    spec:
      {{- with .Values.keycloak.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.chartNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.chartNodeSelector }}
        {{- with .Values.keycloak.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.keycloak.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.keycloak.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.keycloak.podSecurityContext | nindent 8 }}
      containers:
        - name: keycloak
          command:
            - /opt/keycloak/bin/kc.sh
          args:
            - start
            # - --optimized
          securityContext:
            {{- toYaml .Values.keycloak.securityContext | nindent 12 }}
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.keycloak.service.ports.keycloak.containerPort }}
              protocol: {{ .Values.keycloak.service.ports.keycloak.protocol }}
            {{- if .Values.keycloak.tls.enabled }}
            - name: https
              containerPort: {{ .Values.keycloak.service.ports.https.containerPort }}
              protocol: {{ .Values.keycloak.service.ports.https.protocol }}
            {{- end }}
            {{- if or .Values.keycloak.envVars.healthEnabled .Values.keycloak.envVars.metricsEnabled }}
            - name: management
              containerPort: {{ .Values.keycloak.managementService.ports.management.containerPort }}
              protocol: {{ .Values.keycloak.managementService.ports.management.protocol }}
            {{- end }}
          resources:
            {{- toYaml .Values.keycloak.resources | nindent 12 }}
          env:
            - name: KC_DB_URL_HOST
              {{- if .Values.keycloak.useExternalDb }}
              value: {{ .Values.keycloak.envVars.externalDbAddr | quote }}
              {{- else }}
              value: {{ include "database.fullname" . | quote}}
              {{- end }}
            - name: KC_DB_URL_PORT
              {{- if .Values.keycloak.useExternalDb }}
              value: {{ .Values.keycloak.envVars.externalDbPort | quote }}
              {{- else }}
              value: {{ .Values.database.service.ports.db.port | quote }}
              {{- end }}
            {{- with .Values.keycloak.envVars }}
            - name: KC_PROXY_PROTOCOL_ENABLED
              value: {{ .proxyAddressForwarding | quote }}
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_DB
              value: {{ .dbVendor | quote }}
            - name: KC_DB_SCHEMA
              value: {{ .dbSchema | quote }}
            - name: KC_DB_URL_DATABASE
              value: {{ .dbDatabase | quote }}
            - name: KC_HOSTNAME
              value: {{ .hostname | quote }}
            - name: KC_HOSTNAME_STRICT
              value: {{ .hostnamestrict | quote }}
            - name: KC_HTTP_ENABLED
              value: {{ .httpEnabled | quote }}
            - name: KC_HEALTH_ENABLED
              value: {{ .healthEnabled | quote }}
            - name: KC_METRICS_ENABLED
              value: {{ .metricsEnabled | quote }}
            {{- if .httpRelativePath }}
            - name: KC_HTTP_RELATIVE_PATH 
              value: {{ .httpRelativePath }}
            {{- end }}
            {{- end }}
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.adminSecretName" . }}
                  key: username
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.adminSecretName" . }}
                  key: password
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "database.secretName" . }}
                  key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "database.secretName" . }}
                  key: password
            {{- if .Values.keycloak.tls.enabled }}
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: "/etc/certs/cert.pem"
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: "/etc/certs/key.pem"
            {{- end }}
          {{- if .Values.keycloak.tls.enabled }}
          volumeMounts:
            - name: keycloak-cert
              mountPath: /etc/certs
              readOnly: true
          {{- end }}
      {{- if .Values.keycloak.tls.enabled }}
      volumes:
        - name: keycloak-cert
          secret:
            {{- if .Values.keycloak.tls.existingSecret }}
            secretName: {{ .Values.keycloak.tls.existingSecret }}
            {{- else}}
            secretName: {{ include "keycloak.fullname" . }}-secret
            {{- end }}
            items:
              - key: cert.pem
                path: cert.pem
              - key: key.pem
                path: key.pem
      {{- end }}
