name: Publish Docker Compose files in the aeriOS Docker Compose repository (https://github.com/eclipse-aerios/resources/tree/main/docker-compose)

on:
  push:
    branches: ["main"]
    paths: ["docker/**", .github/workflows/publish-docker-compose.yml]
    tags: ["*"]
  pull_request:
    branches: ["main"]
    paths: ["docker/**", .github/workflows/publish-docker-compose.yml]
  workflow_dispatch: {} # allows manual trigger

concurrency:
  group: resources-repository-publish
  cancel-in-progress: false

permissions:
  contents: read

env:
  COMPONENT_NAME: idm
  RESOURCES_REPOSITORY: eclipse-aerios/resources
  RESOURCES_REPOSITORY_BRANCH: main

jobs:
  publish:
    name: Publish Docker compose files
    runs-on: ubuntu-latest

    steps:
      - name: Check out application repository
        uses: actions/checkout@v4

      - name: Check out Docker compose repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.RESOURCES_REPOSITORY }}
          ref: ${{ env.RESOURCES_REPOSITORY_BRANCH }}
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: resources

      - name: Synchronize Docker Compose resources
        run: |
          DESTINATION="resources/docker-compose/${COMPONENT_NAME}"

          mkdir -p "${DESTINATION}"

          rsync -av --delete \
            docker/ \
            "${DESTINATION}/"

      - name: Commit and push
        working-directory: resources
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add "docker-compose/${COMPONENT_NAME}"

          if git diff --cached --quiet; then
            echo "No Docker Compose resources changed."
            exit 0
          fi

          git commit -m "Update ${COMPONENT_NAME} Docker Compose resources"

          git push origin "${RESOURCES_REPOSITORY_BRANCH}"
